### ISSUE TITLE
Exception after updating OWLAPI RDF Library from 2.0.1 to 2.0.2

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#355]
I am not 100% that this is cased by the update of the OWLAPI RDF Library itself or not, but when I opened Protege I got prompted that there is a newer version of the OWLAPI RDF Library available (2.0.2 instead of 2.0.1), and after I chose to update the OWLAPI RDF Library, a message said that my changes will take effect after I restart Protege.
When I closed Protege (not having done any change to any ontology), I got the following exception:

```
Uncaught Exception in thread 'AWT-EventQueue-0' 
java.lang.NoClassDefFoundError: org/protege/editor/owl/ui/inference/ReasonerProgressUI$1
    at org.protege.editor.owl.ui.inference.ReasonerProgressUI.initWindow(ReasonerProgressUI.java:58) ~[na:na]
    at org.protege.editor.owl.ui.inference.ReasonerProgressUI.lambda$reset$217(ReasonerProgressUI.java:151) ~[na:na]
    at org.protege.editor.owl.ui.inference.ReasonerProgressUI$$Lambda$92/510905990.run(Unknown Source) ~[na:na]
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_40]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749) ~[na:1.8.0_40]
    at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:702) ~[na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:696) ~[na:1.8.0_40]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719) ~[na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]
Caused by: java.lang.ClassNotFoundException: Unable to load class 'org.protege.editor.owl.ui.inference.ReasonerProgressUI$1' because the bundle wiring for org.protege.editor.owl is no longer valid.
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1521) ~[org.apache.felix.main.jar:na]
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77) ~[org.apache.felix.main.jar:na]
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993) ~[org.apache.felix.main.jar:na]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_40]
    ... 17 common frames omitted

```

**Comment by matthewhorridge** [comment]
Stale issue because this library has been updated
